openapi: 3.0.1
info:
  title: Mechanical Switches API
  version: 1.0.3
servers:
- url: https://mechswi-api.herokuapp.com/
paths:
  /api/welcome:
    get:
      tags:
      - user
      summary: Welcome message
      description: Sharing the love with welcome message
      operationId: getWelcomeMessage
      responses:
        200:
          description: OK
          content: {}
  /api/user/register:
    post:
      tags:
      - user
      summary: Create new user
      description: Register a new user
      operationId: postNewUser
      requestBody:
        description: The user to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userCreate'
        required: false
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
      x-codegen-request-body-name: User registration
  /api/user/login:
    post:
      tags:
      - user
      summary: Login user
      description: Login as user
      operationId: loginExistingUser
      requestBody:
        description: The user to login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userLogin'
        required: false
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
      x-codegen-request-body-name: User login
  /api/switches/create:
    post:
      tags:
      - switches
      summary: New Switch
      description: Create a new switch
      operationId: postNewSwitch
      requestBody:
        description: Create a new switch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/switchCU'
        required: false
      responses:
        200:
          description: OK
          content: {}
        400:
          description: ACCESS DENIED
          content: {}
        401:
          description: INVALID TOKEN
          content: {}
      security:
      - ApiKeyAuth: []
      x-codegen-request-body-name: Create switch
  /api/switches:
    get:
      tags:
      - switches
      summary: All Switches
      description: Get all the switches
      operationId: getAllSwitches
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/{id}:
    get:
      tags:
      - switches
      summary: Specific switch
      description: Get a specific switch
      operationId: getSingleSwitch
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/type/linear:
    get:
      tags:
      - switches
      - type linear
      summary: Linear switches
      description: Get all linear switches
      operationId: getLinearSwitches
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/type/tactile:
    get:
      tags:
      - switches
      - type tactile
      summary: Tactile switches
      description: Get all tactile switches
      operationId: getTactileSwitches
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/type/clicky:
    get:
      tags:
      - switches
      - type clicky
      summary: Clicky switches
      description: Get all clicky switches
      operationId: getClickySwitches
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/mount/5pin:
    get:
      tags:
      - switches
      - 5pin
      summary: All 5-pin
      description: Get all switches with 5-pin mount
      operationId: getAll5pin
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/mount/3pin:
    get:
      tags:
      - switches
      - 3pin
      summary: All 3-pin
      description: Get all switches with 3-pin mount
      operationId: getAll3pin
      responses:
        200:
          description: OK
          content: {}
        400:
          description: NOT OK
          content: {}
  /api/switches/update/{id}:
    put:
      tags:
      - switches
      - update
      summary: Update switch
      description: Update a specific switch
      operationId: updateSwitch
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Update a switch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/switchCU'
        required: false
      responses:
        200:
          description: OK
          content: {}
        400:
          description: ACCESS DENIED
          content: {}
        401:
          description: INVALID TOKEN
          content: {}
      security:
      - ApiKeyAuth: []
      x-codegen-request-body-name: Update existing switch
  /api/switches/delete/{id}:
    delete:
      tags:
      - switches
      - delete
      summary: Delete switch
      description: Delete a specific switch
      operationId: deleteSwitch
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content: {}
        400:
          description: ACCESS DENIED
          content: {}
        401:
          description: INVALID TOKEN
          content: {}
      security:
      - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: auth-token
      type: apiKey
  schemas:
    userCreate:
      required:
      - email
      - password
      - userName
      type: object
      properties:
        userName:
          type: string
        email:
          type: string
        password:
          type: string
    userLogin:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    switchCU:
      required:
      - actuationForce
      - brand
      - colors
      - lifespan
      - manufacturer
      - model
      - mount
      - preTravel
      - stemStructure
      - switchCollection
      - switchType
      - totalTravel
      type: object
      properties:
        model:
          type: string
        brand:
          type: string
        switchCollection:
          type: string
        switchType:
          type: string
        actuationForce:
          type: string
        preTravel:
          type: string
        totalTravel:
          type: string
        stemStructure:
          type: string
        mount:
          type: string
        lifespan:
          type: string
        colors:
          type: string
        manufacturer:
          type: string